### ISSUE TITLE
Issue with checkbox

### ISSUE THREAD

**Issue by firstsano** [shuriu/ember-do-forms#20]
Hi,
there is problem with displaying object with `boolean` field through `do-control` component as it uses and sets `value`, but for checkbox it should use `checked` property.

Therefore I have to set up something like:
```
{{#do-form model submit=(action 'update' model) as |form|}}
   {{#form.do-field 'hasName' as |f|}}
      {{f.do-control 'checkbox' checked=model.hasName}}
...
```
which is very inconvenient. I wonder if there is a workaround?
Thanks.

**Comment by shuriu** [comment]
Hey @firstsano, I'm using the same pattern and I agree that the ergonomics could be improved.

There are plans of including a checkbox control in the same lines as the `input-field` component for the next version, which should be landing soon.

**Comment by firstsano** [comment]
Ok, thanks. Now I feel relieved that I didn't miss anything, and can use that code for a while :)
